name: Rectangular
version: 0.0.1
author: Citymonstret
main: com.intellectualsites.rectangular.bukkit.RectangularPlugin
commands:
  rectangular:
    aliases: [rect, r, region]
    description: The main command for the rectangular plugin